# Generated by Django 3.2.8 on 2021-12-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BT', 'Biotechnology'), ('CE', 'Chemical Engineering'), ('CE', 'Civil Engineering'), ('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EIE', 'Electronics and Instrumentation Engineering'), ('IEM', 'Industrial Engineering and Management'), ('ISE', 'Information Science and Engineering'), ('MCA', 'Master of Computer Applications'), ('ME', 'Mechanical Engineering'), ('ETE', 'Electronics and Telecommunication Engineering (Telecommunication Engineering)'), ('BSC', 'Basic Sciences')], default='ISE', max_length=3)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
