# Generated by Django 3.2.8 on 2021-12-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('sanc_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.IntegerField(default=2022)),
                ('remarks', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='uname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
