# Generated by Django 3.2.8 on 2021-12-21 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 465221, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='industrial_visit',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mou',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='other_activity',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patent',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 17, 16, 59, 473675, tzinfo=utc)),
        ),
    ]
