# Generated by Django 3.2.8 on 2021-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211209_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('submitted_to', models.CharField(max_length=50)),
                ('budg_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('ON', 'Ongoing')], default='ON', max_length=3)),
            ],
        ),
    ]
