# Generated by Django 3.2.8 on 2021-12-10 05:34

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='grants',
            name='CO_PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_coprinvestigated', to='api.profile'),
        ),
        migrations.AddField(
            model_name='grants',
            name='PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants_prinvestigated', to='api.profile'),
        ),
        migrations.AddField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='proposal',
            name='CO_PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_coprinvestigated', to='api.profile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='PI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals_prinvestigated', to='api.profile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('ON', 'Ongoing')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('event_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('n_stud', models.IntegerField(null=True)),
                ('n_fac', models.IntegerField(null=True)),
                ('n_ind', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 468491, tzinfo=utc))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('ON', 'Ongoing')], max_length=3, null=True)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 470525, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Other_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.IntegerField()),
                ('activity', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 468491, tzinfo=utc))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MoU',
            fields=[
                ('organisation', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mod_col', models.CharField(max_length=25)),
                ('validity', models.IntegerField()),
                ('date', models.DateField()),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 469508, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('mem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('membership', models.CharField(max_length=50)),
                ('association', models.CharField(max_length=50)),
                ('term', models.IntegerField(null=True)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 472559, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('res_person', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('n_stud', models.IntegerField(null=True)),
                ('n_fac', models.IntegerField(null=True)),
                ('n_ind', models.IntegerField(null=True)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Industrial_visit',
            fields=[
                ('visit_no', models.IntegerField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('n_stud', models.IntegerField(null=True)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 471544, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('n_stud', models.IntegerField(null=True)),
                ('n_fac', models.IntegerField(null=True)),
                ('n_ind', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('fund_agency', models.CharField(max_length=50)),
                ('rec_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 462974, tzinfo=utc))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('conference', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('issue', models.IntegerField()),
                ('n_page', models.IntegerField()),
                ('nat_int', models.CharField(choices=[('NAT', 'National'), ('INT', 'International')], max_length=3, null=True)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 469508, tzinfo=utc))),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('n_isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 473572, tzinfo=utc))),
                ('u_id', models.ManyToManyField(to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('date_added', models.DateField(default=datetime.datetime(2021, 12, 10, 5, 34, 30, 469508, tzinfo=utc))),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
