# Generated by Django 4.0 on 2021-12-14 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211210_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='conference',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grants',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='grants',
            name='sanc_amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='industrial_visit',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mou',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='other_activity',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patent',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='talk',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 251724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2021, 12, 14, 7, 13, 18, 236095, tzinfo=utc)),
        ),
    ]
